### PR TITLE
add links to MR and Commit on Edit form

### LINKED ISSUE #152: "commit" and "merge request" links inside the incarnation
it would be nice to have the same links that you can see from main screen - inside the said incarnation:
image

### PR DESCRIPTION
**Pull request by umer4ik**
closes #152

image

### CODE REVIEW

**Comment by defreng** [comment]
mh, can we now move the delete button maybe to the bottom left? Seems a bit dangerously close to those other ones :-D

**Comment by umer4ik** [comment]
@defreng that is why there is a prompt that asks whether you want delete it or not :)

but if it's hard to aim to this buttons, then I'd rather move MR & Commit buttons closer to a status badge

**Comment by defreng** [comment]
@umer4ik also fine with me - I'll leave it up to you...

... as long as you somehow align the heights 😈 😂

**Comment by umer4ik** [comment]
@defreng I enlarged the heights, have a look
image

**Review by defreng — APPROVED** [review]

**Pull request merged**
