### PR TITLE
fix for .png file if it is defined in excluded_files

### PR DESCRIPTION
**Pull request by goldginkgo**
This solves: #384

### CODE REVIEW

**Comment by defreng** [comment]
Thanks for the contribution, @goldginkgo !

Could you maybe add a test that was failing without the patch and now is working?

**Comment by goldginkgo** [comment]
@defreng I've added a test case, please help review again.

**Comment by goldginkgo** [comment]
> looking good! Just some issues now in the CI with the linting / typecheck...
> 
> when fixing this, you can easily check locally whether things are fine using
> 
> ```
> make fmt
> make typecheck
> ```

**Comment by goldginkgo** [comment]
@defreng Thanks for your guidance. Can you check again?

**Comment by defreng** [comment]
Thanks @goldginkgo !!

**Pull request merged**
