### PR TITLE
adding list of future improvement ideas

### PR DESCRIPTION
**Pull request by defreng**

### CODE REVIEW

**Review by timofurrer — COMMENTED** [review]
@defreng While I like the items I'm wondering if it wouldn't make more sense to create individual issues for each of these items ... 

WDYT? 🏓

**Comment by defreng** [comment]
yeah - I was actually wondering the same...

My thought behind adding them to the README was more that these are some very high-level "roadmap" items - without any additional details so far.

What are your thoughts about creating such issues which don't have a lot of content?

**Comment by timofurrer** [comment]
I think I would still prefer the individual issues and maybe create a project board as a roadmap and put them on there and link in the README if this visibility is desired :)

**Comment by defreng** [comment]
well - I actually added them as milestones and issues 🙂

**Pull request closed without merging**
